language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

env:
  # TODO: Remove once kramdown 2.0 ships
  global:
    - KD_VERSION='> 1.17'
  matrix:
    - ROUGE_VERSION='~> 2.0'
    - ROUGE_VERSION='~> 3.0'

branches:
  only:
    - master

before_install:
  - gem update --system
  - gem install kramdown --pre # FIXME: Install kramdown 2.0 once it ships
  - 'gem install rake && rake bootstrap'

notifications:
  email: false
