language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

branches:
  only:
    - master

before_install:
  - gem update --system
  - 'gem install rake && rake bootstrap'

notifications:
  email: false
