language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

# TODO: Remove once kramdown 2.0 ships
env:
  - KD_VERSION='> 1.17'

branches:
  only:
    - master

before_install:
  - gem update --system
  - 'gem install rake && rake bootstrap'

notifications:
  email: false
