language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

env:
  matrix:
    - ROUGE_VERSION='~> 2.0'
    - ROUGE_VERSION='~> 3.0'

branches:
  only:
    - master

before_install:
  - gem update --system
  - gem install kramdown
  - 'gem install rake && rake bootstrap'

notifications:
  email: false
